### ISSUE TITLE
ideep commit broken

### ISSUE THREAD

**Issue by lematt1991** [ebetica/autogradpp#72]
I'm getting errors while trying to checkout the repo

```
git submodule update --init --recursive
error: no such remote ref fb1adc449de61b56e92f8a81e02b91c068209f47
Fetched in submodule path 'pytorch/third_party/ideep', but it did not contain fb1adc449de61b56e92f8a81e02b91c068209f47. Direct fetching of that commit failed.
Failed to recurse into submodule path 'pytorch'
```

It looks like we have a submodule reference to a fork of PyTorch prior to [this](https://github.com/pytorch/pytorch/pull/7191) getting merged.  What do you think is the best way to resolve this?

**Comment by ebetica** [comment]
We're merging this into PyTorch! The API is a bit in flux due to some discussions of what the API should look like in PyTorch, but I'm on commit https://github.com/ebetica/pytorch/tree/9e3f5bb5fd7e418172eb81f90a0a9e59aa8b0222/torch/csrc/api

If you want to keep using the current version, simply update the iDeep inside PyTorch to point to pytorch/ideep, that should solve it.
